name: flow
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev
publish_to: 'none'

# App version: major.minor.patch+buildNumber
version: 1.0.0+1

environment:
  # Supported Dart SDK versions
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Common UI & state management
  cupertino_icons: ^1.0.6
  flutter_bloc: ^9.1.1
  go_router: ^17.0.0

  # Networking
  dio: ^5.9.0

  # JSON serialization
  json_annotation: ^4.9.0

  # Localization / i18n
  slang: ^4.10.0
  slang_flutter: ^4.10.0

  # Debug logging
  logger: ^2.0.2+1

  # Testing utils for Bloc
  bloc_test: ^10.0.0

  # Value comparison
  equatable: ^2.0.5

  # Dependency injection
  get_it: ^9.0.5
  injectable: ^2.3.2

  # App icons generator
  flutter_launcher_icons: ^0.14.4

  # Local storage
  shared_preferences: ^2.2.2

  # Functional programming helpers (Either, Option)
  dartz: ^0.10.1

  # Date / Number formatting
  intl: any

  # Connectivity checker
  internet_connection_checker: ^3.0.1

  # Required for supporting localization in Flutter
  flutter_localizations:
    sdk: flutter

  # Local notifications
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1

  # UUID generator for local IDs
  uuid: ^4.3.3

  # Google login
  google_sign_in: ^7.2.0

  # Environment variables support, reads from .env
  flutter_dotenv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lint rules for best practices
  flutter_lints: ^6.0.0

  # Required for code generation (Json, Injectable)
  build_runner: ^2.4.8

  # Generates JSON serialization code
  json_serializable: ^6.8.0

  # Mocking for tests
  mockito: ^5.4.4


flutter:
  # Allows Material Icons
  uses-material-design: true

  assets:
    # Environment variables (optional: keep out of production VCS)
    - .env

    # Images (png/jpg/svg/gif…)
    - assets/images/

    # Animations (Rive, flare, json, etc.)
    - assets/animations/

    # Lottie animations
    - assets/lottie/

    # Videos (mp4/avi/webm…)
    - assets/videos/

    # Sounds / SFX / music
    - assets/sounds/

    # GIFs inside images/gifs folder
    - assets/images/gifs/

    # Icons (png/svg)
    - assets/images/icons/

    # Illustrations (svg/png artworks)
    - assets/images/illustrations/

    # Logos
    - assets/images/logos/

  fonts:
    # Custom font family
    - family: Source Code Pro
      fonts:
        - asset: assets/fonts/SourceCodePro/SourceCodePro-Regular.ttf
          weight: 400
        - asset: assets/fonts/SourceCodePro/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro/SourceCodePro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceCodePro/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro/SourceCodePro-Light.ttf
          weight: 300

